repos:
  - repo: local
    hooks:
      - id: go-version
        name: go version
        entry: scripts/check-go-version
        language: script
        types: [go]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.2
    hooks:
      - id: markdownlint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt

  - repo: git://github.com/golangci/golangci-lint
    rev: v1.30.0
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: gomod
        name: gomod
        entry: scripts/pre-commit-go-mod
        language: script
        files: go.mod
        pass_filenames: false
