version: 1
update_configs:
  # Keep go modules up to date, batching pull requests weekly
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    # Apply default reviewer @trussworks/waddlers group to PRs
    default_reviewers:
      - "trussworks/waddlers"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
